import { describe, it, expect, vi, afterEach } from 'vitest';
import { registerDiscoveryTools } from '../../src/tools/discovery.js';
import { EventbriteClient } from '../../src/client.js';
import type { DiscoveryClient } from '../../src/discovery.js';
import type { EventbriteTransport } from '../../src/transport.js';
import { createTestHarness, parseToolResult } from '../helpers.js';

// A real CloudFront refusal page, as the edge serves it — the credential never
// reached the API, so the healthcheck must NOT call it rejected.
const CLOUDFRONT_BLOCK = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 3xYqv0aZ1kQ9p_rT8mJ2bW6cN4dE7fG5hI0jK1lM2nO3pQ4rS5tU6v==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>`;

function htmlResponse(status: number, body: string): Response {
  return new Response(body, { status, headers: { 'content-type': 'text/html' } });
}
function jsonResponse(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
}

function transportMock(fetchImpl?: EventbriteTransport['fetch']): EventbriteTransport {
  return {
    start: vi.fn(),
    close: vi.fn(),
    status: vi.fn().mockReturnValue({ role: 'host', port: 37149, extensionConnected: true }),
    fetch: vi.fn(fetchImpl ?? (async () => ({ status: 200, body: '{"categories":[]}', url: '' }))),
    requestJson: vi.fn(),
    readCookies: vi.fn(),
    // Mirrors @fetchproxy/server's runProbe: it swallows the probe's throw and
    // reports { ok, elapsed_ms, bridge, error }.
    runProbe: vi.fn(async (fetchFn: (p: string) => Promise<unknown>, path: string) => {
      const bridge = { role: 'host', port: 37149, last_failure_reason: null };
      try {
        await fetchFn(path);
        return { ok: true, elapsed_ms: 1, bridge };
      } catch (e) {
        return { ok: false, elapsed_ms: 1, bridge, error: { kind: 'other', message: (e as Error).message } };
      }
    }),
  } as unknown as EventbriteTransport;
}

const discovery = {} as DiscoveryClient;

interface Result {
  ok: boolean;
  credential?: { source: string | null; resolved: boolean };
  bridge?: unknown;
  probe: { url?: string; status?: number };
  error?: { kind: string; message: string; detail?: Record<string, unknown> };
  hint: string;
}

describe('eb_healthcheck', () => {
  let harness: Awaited<ReturnType<typeof createTestHarness>> | undefined;

  afterEach(async () => {
    vi.unstubAllGlobals();
    if (harness) await harness.close();
    harness = undefined;
  });

  async function run(client: EventbriteClient, transport: EventbriteTransport | null): Promise<Result> {
    harness = await createTestHarness((server) =>
      registerDiscoveryTools(server, { discovery, transport, client }),
    );
    return parseToolResult(await harness.callTool('eb_healthcheck', {})) as Result;
  }

  it('probes EVENTBRITE_TOKEN against /users/me/ and reports ok', async () => {
    const fetchMock = vi.fn(async () => jsonResponse(200, { id: '1', name: 'A' }));
    vi.stubGlobal('fetch', fetchMock);
    const r = await run(new EventbriteClient({ token: 'tok-ok' }), transportMock());
    expect(r.ok).toBe(true);
    expect(r.credential).toEqual({ source: 'EVENTBRITE_TOKEN', resolved: true });
    expect(fetchMock).toHaveBeenCalledWith('https://www.eventbriteapi.com/v3/users/me/', expect.anything());
    expect(JSON.stringify(r)).not.toContain('tok-ok');
  });

  it('reports credential_rejected on a genuine 401 from the API (control)', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () =>
        jsonResponse(401, { status_code: 401, error: 'INVALID_AUTH', error_description: 'The OAuth token you provided was invalid.' }),
      ),
    );
    const r = await run(new EventbriteClient({ token: 'tok-bad' }), transportMock());
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('credential_rejected');
    expect(r.probe.status).toBe(401);
    expect(JSON.stringify(r)).not.toContain('tok-bad');
  });

  it('reports edge_blocked, not a rejected token, on a CloudFront block page', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => htmlResponse(403, CLOUDFRONT_BLOCK)));
    const r = await run(new EventbriteClient({ token: 'tok-ok' }), transportMock());
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.error?.detail).toEqual({ vendor: 'CloudFront' });
    expect(r.hint).not.toMatch(/re-authenticate/i);
  });

  it('reports edge_blocked on a 401 Cloudflare challenge too', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(
        async () =>
          new Response('<!DOCTYPE html><html><head><title>Just a moment...</title></head><body></body></html>', {
            status: 401,
            headers: { 'content-type': 'text/html', 'cf-mitigated': 'challenge' },
          }),
      ),
    );
    const r = await run(new EventbriteClient({ token: 'tok-ok' }), transportMock());
    expect(r.error?.kind).toBe('edge_blocked');
  });

  it('reports http on an upstream 5xx', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => jsonResponse(500, { error: 'INTERNAL_ERROR' })));
    const r = await run(new EventbriteClient({ token: 'tok-ok' }), transportMock());
    expect(r.error?.kind).toBe('http');
  });

  it('reports transport when the API is unreachable', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => Promise.reject(new TypeError('fetch failed'))));
    const r = await run(new EventbriteClient({ token: 'tok-ok' }), transportMock());
    expect(r.error?.kind).toBe('transport');
  });

  it('reports no_credential WITHOUT probing when there is no token and no bridge', async () => {
    const orig = process.env.EVENTBRITE_TOKEN;
    delete process.env.EVENTBRITE_TOKEN;
    const fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);
    try {
      const r = await run(new EventbriteClient(), null);
      expect(r.ok).toBe(false);
      expect(r.error?.kind).toBe('no_credential');
      expect(fetchMock).not.toHaveBeenCalled();
    } finally {
      if (orig !== undefined) process.env.EVENTBRITE_TOKEN = orig;
    }
  });

  describe('with no token on stdio (discovery rides the bridge)', () => {
    let orig: string | undefined;
    const withoutToken = async <T>(fn: () => Promise<T>): Promise<T> => {
      orig = process.env.EVENTBRITE_TOKEN;
      delete process.env.EVENTBRITE_TOKEN;
      try {
        return await fn();
      } finally {
        if (orig !== undefined) process.env.EVENTBRITE_TOKEN = orig;
      }
    };

    it('diagnoses the bridge and still says the token is missing', async () => {
      const fetchMock = vi.fn();
      vi.stubGlobal('fetch', fetchMock);
      const transport = transportMock();
      const r = await withoutToken(() => run(new EventbriteClient(), transport));
      expect(r.bridge).toBeDefined();
      expect(r.credential).toEqual({ source: null, resolved: false });
      expect(r.hint).toMatch(/EVENTBRITE_TOKEN is not set/);
      expect(transport.fetch).toHaveBeenCalledWith({ path: '/api/v3/categories/', method: 'GET' });
      expect(fetchMock).not.toHaveBeenCalled();
    });

    it('reports edge_blocked when the bridge probe meets a block page', async () => {
      const transport = transportMock(async () => ({ status: 403, body: CLOUDFRONT_BLOCK, url: '' }));
      const r = await withoutToken(() => run(new EventbriteClient(), transport));
      expect(r.ok).toBe(false);
      expect(r.error?.kind).toBe('edge_blocked');
    });

    it('reports http (not edge_blocked) for a plain bridge-path 404 (control)', async () => {
      const transport = transportMock(async () => ({ status: 404, body: '{"error":"NOT_FOUND"}', url: '' }));
      const r = await withoutToken(() => run(new EventbriteClient(), transport));
      expect(r.ok).toBe(false);
      expect(r.error?.kind).not.toBe('edge_blocked');
    });
  });
});
